title: Neural Extraction Framework in DBpedia
description: A GSoC 2024 project page
theme: just-the-docs

url: https://smilingprogrammer.github.io/GSoC-2024-blog

aux_links:
  Project's GitHub Repo: https://github.com/dbpedia/neural-extraction-framework
